# Generated by Django 5.2.9 on 2025-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='축제명')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='카테고리')),
                ('address', models.CharField(max_length=500, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='연락처')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('event_start_date', models.CharField(blank=True, max_length=20, verbose_name='행사 시작일')),
                ('event_end_date', models.CharField(blank=True, max_length=20, verbose_name='행사 종료일')),
                ('start_month', models.IntegerField(blank=True, help_text='1-12', null=True, verbose_name='시작 월')),
                ('end_month', models.IntegerField(blank=True, help_text='1-12', null=True, verbose_name='종료 월')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
                ('content_id', models.CharField(help_text='외부 API Content ID', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '축제',
                'verbose_name_plural': '축제 목록',
                'db_table': 'festivals',
                'ordering': ['start_month', 'title'],
            },
        ),
    ]
