# Generated by Django 5.2.9 on 2025-12-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='장소명', max_length=255)),
                ('place_type', models.CharField(choices=[('tourist', '관광지'), ('festival', '축제/행사'), ('restaurant', '맛집'), ('cafe', '카페'), ('accommodation', '숙박')], default='tourist', max_length=20)),
                ('address', models.CharField(help_text='주소', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('content_id', models.CharField(help_text='외부 API Content ID', max_length=50, unique=True)),
                ('region', models.CharField(help_text='지역', max_length=100)),
                ('event_start_date', models.DateField(blank=True, help_text='행사 시작일', null=True)),
                ('event_end_date', models.DateField(blank=True, help_text='행사 종료일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='places.place')),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
