# Generated by Django 5.2.9 on 2025-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, help_text='세부 카테고리 (예: 사찰, 해수욕장, 한식 등)', max_length=100),
        ),
    ]
