# Generated by Django 5.2.9 on 2025-12-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='여행 제목', max_length=255)),
                ('budget', models.IntegerField(help_text='예산')),
                ('start_date', models.DateField(help_text='여행 시작일')),
                ('end_date', models.DateField(help_text='여행 종료일')),
                ('region', models.CharField(help_text='여행 지역', max_length=100)),
                ('travel_style', models.CharField(help_text='여행 스타일', max_length=100)),
                ('accommodation_type', models.CharField(choices=[('hotel', '호텔'), ('motel', '모텔'), ('pension', '펜션'), ('guesthouse', '게스트하우스')], default='motel', max_length=20)),
                ('is_generated', models.BooleanField(default=False, help_text='AI 생성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'travel_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='여행 일차')),
                ('date', models.DateField(help_text='일정 날짜')),
                ('description', models.TextField(blank=True, help_text='일정 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.travelplan')),
            ],
            options={
                'db_table': 'itineraries',
                'ordering': ['day_number'],
                'unique_together': {('travel_plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='방문 순서')),
                ('visit_time', models.TimeField(blank=True, help_text='방문 시간', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='체류 시간 (분)', null=True)),
                ('notes', models.TextField(blank=True, help_text='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.itinerary')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_places', to='places.place')),
            ],
            options={
                'db_table': 'itinerary_places',
                'ordering': ['order'],
                'unique_together': {('itinerary', 'order')},
            },
        ),
    ]
