# Generated by Django 5.2.9 on 2025-12-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="accommodation_info",
            field=models.JSONField(blank=True, default=dict, help_text="숙소 정보"),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="attractions",
            field=models.JSONField(
                blank=True, default=list, help_text="관광지 목록 (이름, 시간, 설명)"
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="estimated_cost",
            field=models.IntegerField(
                blank=True, help_text="일차별 예상 비용", null=True
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="events_info",
            field=models.JSONField(
                blank=True, default=list, help_text="축제/행사 정보"
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="meals_info",
            field=models.JSONField(
                blank=True, default=dict, help_text="식사 정보 (아침, 점심, 저녁)"
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="transportation_info",
            field=models.JSONField(blank=True, default=dict, help_text="교통수단 정보"),
        ),
    ]
