# Generated by Django 5.2.9 on 2025-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_itinerary_accommodation_info_itinerary_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='people_count',
            field=models.IntegerField(default=1, help_text='인원 수'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.IntegerField(help_text='예산 (총 예산)'),
        ),
    ]
