# Generated by Django 5.2.9 on 2025-12-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_travelplan_people_count_alter_travelplan_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='departure_location',
            field=models.CharField(default='서울특별시', help_text='출발지', max_length=100),
        ),
    ]
