# Generated by Django 5.2.9 on 2025-12-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_travelplan_departure_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='추천 여부'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='rating',
            field=models.IntegerField(blank=True, help_text='평점 (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='recommended_at',
            field=models.DateTimeField(blank=True, help_text='추천 일시', null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='review',
            field=models.TextField(blank=True, help_text='후기'),
        ),
    ]
