# Generated by Django 5.2.9 on 2025-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, help_text='카카오 고유 ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('kakao', 'Kakao')], default='normal', help_text='로그인 타입', max_length=20),
        ),
    ]
