# Generated by Django 5.2.9 on 2025-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_kakao_id_user_login_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="구글 고유 ID",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("kakao", "Kakao"),
                    ("google", "Google"),
                ],
                default="normal",
                help_text="로그인 타입",
                max_length=20,
            ),
        ),
    ]
